wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.21.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1658265572
    t:
      1:
      - 1
      - 9
      - 11
      - 40
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 40
      - 49
      - 55
      4: 3.10.5
      5: 0.12.21
      6: 4.21.0.dev0
      8:
      - 4
      - 5
